x-payment-service-environment: &payment-service-environment
  REDIS_URL: ${REDIS_URL}
  ASYNC_DB_URL: ${ASYNC_DB_URL}
  SYNC_DB_URL: ${SYNC_DB_URL}
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
  PYTHONPATH: /app

services:
  payment-service-redis:
    image: redis:7
    container_name: "payment-service-redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    networks:
      - payment-service-network

  payment-service-database:
    image: postgres:17
    container_name: "payment-service-database"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
    networks:
      - payment-service-network

  payment-service-app:
    build: .
    container_name: "payment-service"
    environment:
      <<: *payment-service-environment
    depends_on:
      payment-service-database:
        condition: service_healthy
      payment-service-redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - payment-service-network


  #
  # CELERY
  #

  payment-service-celery-broker:
    image: rabbitmq:3-management
    container_name: "payment-service-celery-broker"
    environment:
      - RABBITMQ_DEFAULT_USER=${CELERY_RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${CELERY_RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - payment-service-network

  payment-service-celery-worker:
    build: .
    container_name: "payment-service-celery-worker"
    command: celery -A src.config.celery worker -l info
    volumes:
      - ./:/app
    environment:
      <<: *payment-service-environment
    depends_on:
      payment-service-database:
        condition: service_healthy
      payment-service-celery-broker:
        condition: service_healthy
    networks:
      - payment-service-network


networks:
  payment-service-network:
    driver: bridge
