
services:
  payment-service-redis:
    image: redis:7
    container_name: "payment-service-redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    networks:
      - payment-service-network

  payment-service-database:
    image: postgres:17
    container_name: "payment-service-database"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
    networks:
      - payment-service-network

  payment-service-app:
    build: .
    container_name: "payment-service"
    environment:
      DB_URL: ${DB_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      MIGRATIONS_DB_URL: ${MIGRATIONS_DB_URL}
    depends_on:
      payment-service-database:
        condition: service_healthy
      payment-service-redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - payment-service-network

networks:
  payment-service-network:
    driver: bridge
