"""Initial migrations (User UserBalance PaymentTransaction)

Revision ID: 65be4b9b3ecc
Revises: 
Create Date: 2026-02-23 12:11:57.776628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65be4b9b3ecc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=63), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'FREEZED', name='userstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'AUD', 'CAD', 'ARS', 'PLN', 'BTC', 'ETH', 'DOGE', 'USDT', 'BYN', 'RUB', name='currency'), server_default='USD', nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'processed', 'PROCESSING', 'FAILED', 'CANCELLED', name='transactionstatus'), server_default='PENDING', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_transactions_check_transaction_amount_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_table('users_balances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'AUD', 'CAD', 'ARS', 'PLN', 'BTC', 'ETH', 'DOGE', 'USDT', 'BYN', 'RUB', name='currency'), server_default='USD', nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_users_balances_check_balance_amount_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_balances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_balances')),
    sa.UniqueConstraint('user_id', 'currency', name='uq_user_balance_user_currency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_balances')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
