"""Add from_user, to_user fields

Revision ID: 661c2b31199d
Revises: 67ddc8e3bcb2
Create Date: 2026-02-24 15:26:35.805732

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "661c2b31199d"
down_revision: Union[str, Sequence[str], None] = "67ddc8e3bcb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = postgresql.ENUM("PENDING", "PROCESSED", "RALLBACKED", name="paymenttransactionstatus")
    payment_status_enum.create(op.get_bind())
    op.execute("ALTER TABLE transactions ALTER COLUMN status DROP DEFAULT")
    op.add_column("transactions", sa.Column("from_user_id", sa.UUID(), nullable=False))
    op.add_column("transactions", sa.Column("to_user_id", sa.UUID(), nullable=False))
    op.alter_column(
        "transactions",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "processed", "PROCESSING", "FAILED", "CANCELLED", name="transactionstatus"
        ),
        type_=sa.Enum("PENDING", "PROCESSED", "RALLBACKED", name="paymenttransactionstatus"),
        existing_nullable=False,
        postgresql_using="status::text::paymenttransactionstatus",
    )
    op.execute("ALTER TABLE transactions ALTER COLUMN status SET DEFAULT 'PENDING'::paymenttransactionstatus")
    op.drop_constraint(op.f("fk_transactions_user_id_users"), "transactions", type_="foreignkey")
    op.create_foreign_key(op.f("fk_transactions_to_user_id_users"), "transactions", "users", ["to_user_id"], ["id"])
    op.create_foreign_key(op.f("fk_transactions_from_user_id_users"), "transactions", "users", ["from_user_id"], ["id"])
    op.drop_column("transactions", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    old_status_enum = postgresql.ENUM(
        "PENDING", "processed", "PROCESSING", "FAILED", "CANCELLED", name="transactionstatus"
    )
    old_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("transactions", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("fk_transactions_from_user_id_users"), "transactions", type_="foreignkey")
    op.drop_constraint(op.f("fk_transactions_to_user_id_users"), "transactions", type_="foreignkey")
    op.create_foreign_key(op.f("fk_transactions_user_id_users"), "transactions", "users", ["user_id"], ["id"])
    op.alter_column(
        "transactions",
        "status",
        existing_type=sa.Enum("PENDING", "PROCESSED", "RALLBACKED", name="paymenttransactionstatus"),
        type_=postgresql.ENUM("PENDING", "processed", "PROCESSING", "FAILED", "CANCELLED", name="transactionstatus"),
        existing_nullable=False,
        postgresql_using="status::text::transactionstatus",
    )

    op.execute("ALTER TABLE transactions ALTER COLUMN status SET DEFAULT 'PENDING'::transactionstatus")
    op.drop_column("transactions", "to_user_id")
    op.drop_column("transactions", "from_user_id")
    new_status_enum = postgresql.ENUM(name="paymenttransactionstatus")
    new_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
